# Site settings
title: Goodstar Demolition
description: 'Business Card Page'
url: 'http://goodstardemolition.com'
baseurl: ''
profilepic: '/images/goodstar-logo.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '322afc402b.js'

author:
  name: 'Goodstar Demolition'
  email: 'info@goodstardemolition.com'
  twitter_username: goodstardemolition
  facebook_username: Goodstar-Demolition-103951561430811
  linkedin_username: goodstardemolition

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
